### ISSUE TITLE
Circular dependency when using authentication with customMessages in HttpApi

### ISSUE THREAD

**Issue by jumic** [taimos/cdk-serverless#116]
Hi,

#### Do you want to request a feature or report a bug?
bug

#### What is the current behavior?
`cdk deploy` fails with circular dependency error:
```
my-http-stack-dev failed: Error [ValidationError]: Circular dependency between resources: [ApiAuthenticationGroupadmin1F3B381D, ApiFnremoveTodo3270A2EC, ApiFngetTodoById6950F289, ApiDELETEtodosidHttpIntegration01b2222bbca1e140051e74b75d02a6799AB1AEF8, ApiDELETEtodosid87BC86DA, ApiGETtodos9447D15A, ApiPOSTtodosDBE932CC, ApiGETtodosmyhttpstackdevApiGETtodos6F4DA541PermissionD940D7E9, ApiDELETEtodosidmyhttpstackdevApiDELETEtodosidCB5EB443PermissionB8D09DC9, ApiFnaddTodo2C053AD6, ApiAuthenticationCustomMessageFunctionCustomMessageCognito6BA0E215, ApiMonitoringDashboard86C659C4, ApiFngetTodos2277752E, ApiGETtodosidmyhttpstackdevApiGETtodosid594DCC8APermission3A22A070, ApiAuthenticationUserPool7FA29541, ApiGETtodosidHttpIntegration7b25c63f258d2c5123860c9dc5fac2193E95C7A6, ApiGETtodosid3DAAA533, ApiPOSTtodosmyhttpstackdevApiPOSTtodos997E2D9DPermission5AEBEF5E, ApiPOSTtodosHttpIntegration554586fb156f3766b3c7c3e8145235e46F587D89, ApiAuthenticationGroupmoderators200792EB, ApiAuthenticationCustomMessageFunction95A5B159, ApiGETtodosHttpIntegration1ff291e4d950d72be84694163c73b7dbFC2116E5]
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-06-19T19:09:33.601Z,
  requestId: '2591ca80-0195-4698-8d8d-aff09c54ade7',
  statusCode: 400,
  retryable: false,
  retryDelay: 35.58554566236416
}
```

#### If the current behavior is a bug, please provide the steps to reproduce it.
I checked out the demo project: https://github.com/taimos/cdk-serverless-demo-http

In .projenrc.js, I specified the cdk-serverless version number to use the current version:
```
deps: [
    'cdk-serverless@0.1.42',
  ],
```

In main.ts, I added the authentication configuration to the HttpApi:
```
authentication: {
        groups: {
          admin: 'Admins',
          moderators: 'Mods',
        },
        triggers: {
          customMessages: true,
        },
      },
```

#### What is the expected behavior?
CDK stack should be deployed without circular dependency error.

#### Which versions of CDK Serverless are affected by this issue? Did this work in previous versions?
cdk-serverless: 0.1.42
It worked in previous versions (0.1.2).

If I remove line `customMessages: true,` from main.ts, the issue doesn't appear and the stack will be deployed successfully.

**Comment by hoegertn** [comment]
Thanks, I will look into it. This definitely worked before so I assume a breaking change in CDK as the reason.

**Comment by hoegertn** [comment]
I upgraded several packages for this project. Can you retry? I could not reproduce it now

**Comment by jumic** [comment]
Thanks. Unfortunately, I still get the same error message with the new version of the demo project.

I tried the same using the Gitpod IDE to make sure, the issue isn't related to my local configuration.

I opened Gitpod with the Gitpod button on the example project page: https://github.com/taimos/cdk-serverless-demo-http

Next, I installed the necessary tools:
```
yarn install
sudo apt-get update
sudo apt-get -y install awscli
npm i -g aws-cdk
```

In main.ts, I added the authentication:
```
authentication: {
        groups: {
          admin: 'Admins',
          moderators: 'Mods',
        },
        triggers: {
          customMessages: true,
        },
      },
```

I changed the values for `domainName` and `account` to my own values.

Then, I configured the CLI credentials with `aws configure` and executed the deployment with `cdk deploy`. The same error occurs:
```
 my-http-stack-dev failed: Error [ValidationError]: Circular dependency between resources: [ApiAuthenticationGroupadmin1F3B381D, ApiFnremoveTodo3270A2EC, ApiFngetTodoById6950F289, ApiDELETEtodosidHttpIntegration01b2222bbca1e140051e74b75d02a6799AB1AEF8, ApiDELETEtodosid87BC86DA, ApiGETtodos9447D15A, ApiPOSTtodosDBE932CC, ApiGETtodosmyhttpstackdevApiGETtodos6F4DA541PermissionD940D7E9, ApiDELETEtodosidmyhttpstackdevApiDELETEtodosidCB5EB443PermissionB8D09DC9, ApiFnaddTodo2C053AD6, ApiAuthenticationCustomMessageFunctionCustomMessageCognito6BA0E215, ApiMonitoringDashboard86C659C4, ApiFngetTodos2277752E, ApiGETtodosidmyhttpstackdevApiGETtodosid594DCC8APermission3A22A070, ApiAuthenticationUserPool7FA29541, ApiGETtodosidHttpIntegration7b25c63f258d2c5123860c9dc5fac2193E95C7A6, ApiGETtodosid3DAAA533, ApiPOSTtodosmyhttpstackdevApiPOSTtodos997E2D9DPermission5AEBEF5E, ApiPOSTtodosHttpIntegration554586fb156f3766b3c7c3e8145235e46F587D89, ApiAuthenticationGroupmoderators200792EB, ApiAuthenticationCustomMessageFunction95A5B159, ApiGETtodosHttpIntegration1ff291e4d950d72be84694163c73b7dbFC2116E5]
    at Request.extractError (/home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/gitpod/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-06-20T10:09:37.662Z,
  requestId: 'd46dad82-a733-4dae-9c81-e7fef09b637b',
  statusCode: 400,
  retryable: false,
  retryDelay: 288.8555753897697
}
```

After deleting line `customMessages: true,`, the deployment works fine again.

Can you reproduce it this way?

**Comment by hoegertn** [comment]
I think I found it. The Lambda function for the custom message and the user pool are cyclic. I will push a new version that fixes this.

**Comment by hoegertn** [comment]
Hopefully, version 0.1.44 fixes this.

**Comment by jumic** [comment]
Thanks, this solved the issue. 👍 I can deploy my Stack successfully with the new version.

**Comment by hoegertn** [comment]
Thanks for finding this issue
